// generated by `Mimix86.Generators.Opcodes.OpcodesGenerator`
// any changes will be lost on next generation

using static Mimix86.Core.Cpu.Decoder.DecodeFlags;
using static Mimix86.Core.Cpu.Decoder.Opcode;

namespace Mimix86.Core.Cpu.Decoder;

// CS1591 is XML doc comments
#pragma warning disable CS1591
// ReSharper disable InconsistentNaming

/// <summary>
/// Enumerates all the supported opcodes by their location in the various opmaps.
/// </summary>
public static class OpcodeMap
{
    public static readonly OpcodeMapEntry[] OpcodeUndefined =
    {
        new(Undefined, .., DecodeFlags.None),
    };

    public static readonly OpcodeMapEntry[] Opcode00 =
    {
        new(AddEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode01 =
    {
        new(AddEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode02 =
    {
        new(AddGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode03 =
    {
        new(AddGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode04 =
    {
        new(AddALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode05 =
    {
        new(AddAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode06 =
    {
        new(PushES, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode07 =
    {
        new(PopES, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode08 =
    {
        new(OrEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode09 =
    {
        new(OrEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode0A =
    {
        new(OrGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode0B =
    {
        new(OrGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode0C =
    {
        new(OrALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode0D =
    {
        new(OrAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode0E =
    {
        new(PushCS, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode0F =
    {
        new(PopCS, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode10 =
    {
        new(AdcEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode11 =
    {
        new(AdcEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode12 =
    {
        new(AdcGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode13 =
    {
        new(AdcGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode14 =
    {
        new(AdcALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode15 =
    {
        new(AdcAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode16 =
    {
        new(PushSS, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode17 =
    {
        new(PopSS, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode18 =
    {
        new(SbbEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode19 =
    {
        new(SbbEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode1A =
    {
        new(SbbGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode1B =
    {
        new(SbbGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode1C =
    {
        new(SbbALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode1D =
    {
        new(SbbAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode1E =
    {
        new(PushDS, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode1F =
    {
        new(PopDS, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode20 =
    {
        new(AndEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode21 =
    {
        new(AndEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode22 =
    {
        new(AndGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode23 =
    {
        new(AndGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode24 =
    {
        new(AndALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode25 =
    {
        new(AndAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode27 =
    {
        new(Daa, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode28 =
    {
        new(SubEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode29 =
    {
        new(SubEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode2A =
    {
        new(SubGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode2B =
    {
        new(SubGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode2C =
    {
        new(SubALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode2D =
    {
        new(SubAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode2F =
    {
        new(Das, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode30 =
    {
        new(XorEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode31 =
    {
        new(XorEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode32 =
    {
        new(XorGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode33 =
    {
        new(XorGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode34 =
    {
        new(XorALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode35 =
    {
        new(XorAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode37 =
    {
        new(Aaa, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode38 =
    {
        new(CmpEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode39 =
    {
        new(CmpEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode3A =
    {
        new(CmpGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode3B =
    {
        new(CmpGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode3C =
    {
        new(CmpALIb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode3D =
    {
        new(CmpAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode3F =
    {
        new(Aas, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode40x47 =
    {
        new(IncZw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode48x4F =
    {
        new(DecZw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode50x57 =
    {
        new(PushZw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode58x5F =
    {
        new(PopZw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode60 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode61 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode62 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode63 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode64 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode65 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode66 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode67 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode68 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode69 =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode6A =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode6B =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode6C =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode6D =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode6E =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode6F =
    {
        new(JccJb, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode70x7F =
    {
        new(JccJb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode80 =
    {
        new(AdcEbIb, .., Reg2),
        new(AddEbIb, .., Reg0),
        new(AndEbIb, .., Reg4),
        new(CmpEbIb, .., Reg7),
        new(OrEbIb, .., Reg1),
        new(SbbEbIb, .., Reg3),
        new(SubEbIb, .., Reg5),
        new(XorEbIb, .., Reg6),
    };

    public static readonly OpcodeMapEntry[] Opcode81 =
    {
        new(AdcEwIw, .., Reg2),
        new(AddEwIw, .., Reg0),
        new(AndEwIw, .., Reg4),
        new(CmpEwIw, .., Reg7),
        new(OrEwIw, .., Reg1),
        new(SbbEwIw, .., Reg3),
        new(SubEwIw, .., Reg5),
        new(XorEwIw, .., Reg6),
    };

    public static readonly OpcodeMapEntry[] Opcode83 =
    {
        new(AdcEwIb, .., Reg2),
        new(AddEwIb, .., Reg0),
        new(AndEwIb, .., Reg4),
        new(CmpEwIb, .., Reg7),
        new(OrEwIb, .., Reg1),
        new(SbbEwIb, .., Reg3),
        new(SubEwIb, .., Reg5),
        new(XorEwIb, .., Reg6),
    };

    public static readonly OpcodeMapEntry[] Opcode84 =
    {
        new(TestEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode85 =
    {
        new(TestEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode86 =
    {
        new(XchgEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode87 =
    {
        new(XchgEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode88 =
    {
        new(MovEbGb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode89 =
    {
        new(MovEwGw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode8A =
    {
        new(MovGbEb, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode8B =
    {
        new(MovGwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode8C =
    {
        new(MovEwSw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode8D =
    {
        new(LeaGwM, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode8E =
    {
        new(MovSwEw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode8F =
    {
        new(PopEw, ..0),
    };

    public static readonly OpcodeMapEntry[] Opcode90 =
    {
        new(Nop, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode90x97 =
    {
        new(XchgAXZw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode98 =
    {
        new(Cbw, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode99 =
    {
        new(Cwd, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode9A =
    {
        new(CallApww, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode9B =
    {
        new(Wait, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode9C =
    {
        new(Pushf, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode9D =
    {
        new(Popf, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode9E =
    {
        new(Sahf, ..),
    };

    public static readonly OpcodeMapEntry[] Opcode9F =
    {
        new(Lahf, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA0 =
    {
        new(MovALOb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA1 =
    {
        new(MovAXOw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA2 =
    {
        new(MovObAL, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA3 =
    {
        new(MovOwAX, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA4 =
    {
        new(Movsb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA5 =
    {
        new(Movsw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA6 =
    {
        new(Cmpsb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA7 =
    {
        new(Cmpsw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA8 =
    {
        new(TestALIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeA9 =
    {
        new(TestAXIw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeAA =
    {
        new(Stosb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeAB =
    {
        new(Stosw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeAC =
    {
        new(Lodsb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeAD =
    {
        new(Lodsw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeAE =
    {
        new(Scasb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeAF =
    {
        new(Scasw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeB0xB7 =
    {
        new(MovZbIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeB8xBF =
    {
        new(MovZwIw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeC0 =
    {
        new(RetIw, ..0),
    };

    public static readonly OpcodeMapEntry[] OpcodeC1 =
    {
        new(Ret, ..0),
    };

    public static readonly OpcodeMapEntry[] OpcodeC2 =
    {
        new(RetIw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeC3 =
    {
        new(Ret, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeC4 =
    {
        new(LesGwMw, .., ModMem),
    };

    public static readonly OpcodeMapEntry[] OpcodeC5 =
    {
        new(LdsGwMw, .., ModMem),
    };

    public static readonly OpcodeMapEntry[] OpcodeC6 =
    {
        new(MovEbIb, .., Reg0),
    };

    public static readonly OpcodeMapEntry[] OpcodeC7 =
    {
        new(MovEwIw, .., Reg0),
    };

    public static readonly OpcodeMapEntry[] OpcodeC8 =
    {
        new(RetfIw, ..0),
    };

    public static readonly OpcodeMapEntry[] OpcodeC9 =
    {
        new(Retf, ..0),
    };

    public static readonly OpcodeMapEntry[] OpcodeCA =
    {
        new(RetfIw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeCB =
    {
        new(Retf, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeCC =
    {
        new(Int3, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeCD =
    {
        new(IntIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeCE =
    {
        new(Into, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeCF =
    {
        new(Iret, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeD0 =
    {
        new(RclEb1, .., Reg2),
        new(RcrEb1, .., Reg3),
        new(RolEb1, .., Reg0),
        new(RorEb1, .., Reg1),
        new(SarEb1, .., Reg7),
        new(SetmoEb1, ..0, Reg6),
        new(ShlEb1, .., Reg4),
        new(ShrEb1, .., Reg5),
    };

    public static readonly OpcodeMapEntry[] OpcodeD1 =
    {
        new(RclEw1, .., Reg2),
        new(RcrEw1, .., Reg3),
        new(RolEw1, .., Reg0),
        new(RorEw1, .., Reg1),
        new(SarEw1, .., Reg7),
        new(SetmoEw1, ..0, Reg6),
        new(ShlEw1, .., Reg4),
        new(ShrEw1, .., Reg5),
    };

    public static readonly OpcodeMapEntry[] OpcodeD2 =
    {
        new(RclEbCL, .., Reg2),
        new(RcrEbCL, .., Reg3),
        new(RolEbCL, .., Reg0),
        new(RorEbCL, .., Reg1),
        new(SarEbCL, .., Reg7),
        new(SetmoEbCL, ..0, Reg6),
        new(ShlEbCL, .., Reg4),
        new(ShrEbCL, .., Reg5),
    };

    public static readonly OpcodeMapEntry[] OpcodeD3 =
    {
        new(RclEwCL, .., Reg2),
        new(RcrEwCL, .., Reg3),
        new(RolEwCL, .., Reg0),
        new(RorEwCL, .., Reg1),
        new(SarEwCL, .., Reg7),
        new(SetmoEwCL, ..0, Reg6),
        new(ShlEwCL, .., Reg4),
        new(ShrEwCL, .., Reg5),
    };

    public static readonly OpcodeMapEntry[] OpcodeD4 =
    {
        new(AamIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeD5 =
    {
        new(AadIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeD6 =
    {
        new(Salc, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeD7 =
    {
        new(Xlat, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE0 =
    {
        new(LoopneJb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE1 =
    {
        new(LoopeJb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE2 =
    {
        new(LoopJb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE3 =
    {
        new(JcxzJb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE4 =
    {
        new(InALIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE5 =
    {
        new(InAXIb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE6 =
    {
        new(OutIbAL, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE7 =
    {
        new(OutIbAX, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE8 =
    {
        new(CallJw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeE9 =
    {
        new(JmpJw, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeEA =
    {
        new(JmpApww, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeEB =
    {
        new(JmpJb, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeEC =
    {
        new(InALDX, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeED =
    {
        new(InAXDX, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeEE =
    {
        new(OutDXAL, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeEF =
    {
        new(OutDXAX, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeF4 =
    {
        new(Hlt, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeF5 =
    {
        new(Cmc, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeF6 =
    {
        new(DivEb, .., Reg6),
        new(IdivEb, .., Reg7),
        new(ImulEb, .., Reg5),
        new(MulEb, .., Reg4),
        new(NegEb, .., Reg3),
        new(NotEb, .., Reg2),
        new(TestEbIb, .., Reg0),
        new(TestEbIb, .., Reg1),
    };

    public static readonly OpcodeMapEntry[] OpcodeF7 =
    {
        new(DivEw, .., Reg6),
        new(IdivEw, .., Reg7),
        new(ImulEw, .., Reg5),
        new(MulEw, .., Reg4),
        new(NegEw, .., Reg3),
        new(NotEw, .., Reg2),
        new(TestEwIw, .., Reg0),
        new(TestEwIw, .., Reg1),
    };

    public static readonly OpcodeMapEntry[] OpcodeF8 =
    {
        new(Clc, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeF9 =
    {
        new(Stc, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeFA =
    {
        new(Cli, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeFB =
    {
        new(Sti, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeFC =
    {
        new(Cld, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeFD =
    {
        new(Std, ..),
    };

    public static readonly OpcodeMapEntry[] OpcodeFE =
    {
        new(CallEw, ..0, Reg2),
        new(CallMpww, ..0, ModMem | Reg3),
        new(DecEb, .., Reg1),
        new(IncEb, .., Reg0),
        new(JmpEw, ..0, Reg4),
        new(JmpMpww, ..0, ModMem | Reg5),
        new(PushEw, ..0, Reg6),
        new(PushEw, ..0, Reg7),
    };

    public static readonly OpcodeMapEntry[] OpcodeFF =
    {
        new(CallEw, .., Reg2),
        new(CallMpww, .., ModMem | Reg3),
        new(DecEw, .., Reg1),
        new(IncEw, .., Reg0),
        new(JmpEw, .., Reg4),
        new(JmpMpww, .., ModMem | Reg5),
        new(PushEw, .., Reg6),
        new(PushEw, ..0, Reg7),
    };
}
